### ISSUE TITLE
80433 trace trap  xcode-arch -p

### ISSUE THREAD

**Issue by Pavel-Laukhin** [417-72KI/xcode-arch#6]
Hi!

I have a trouble with Xcode 14.0.0-Beta.6. It says "80023 trace trap  xcode-arch -p" when I try to execute "xcode-arch -p". Also I have the same answer on my attempt with "DEVELOPER_DIR=/Applications/Xcode-14.0.0-Beta.6.app xcode-arch -p". 

Can you help?

**Comment by 417-72KI** [comment]
Sorry for late.
I found when some old Xcode has been removed, it causes a crash.

Probably fixed in #7.

**Comment by 417-72KI** [comment]
Released on [0.0.2](https://github.com/417-72KI/xcode-arch/releases/tag/0.0.2)
